ENV:
  NAME: "TASK"
COMMIT:
  - KEY: "REFERENCE"
    LABEL: "Task ID"
    PROJECT_NAME: "{{NAME}}"
  - KEY: "CHANGE"
    LABEL: "Type of change"
    OPTIONS:
      - VALUE: "feat"
        DESC: "👷A new feature"
      - VALUE: "fix"
        DESC: "🐛A bug fix"
      - VALUE: "docs"
        DESC: "📝Documentation only changes"
      - VALUE: "style"
        DESC: "🎨Changes that do not affect the meaning of the code"
      - VALUE: "refactor"
        DESC: "♻️A code change that neither fixes a bug nor adds a feature"
      - VALUE: "perf"
        DESC: "⚡️A code change that improves performance"
      - VALUE: "test"
        DESC: "✅Adding missing tests or correcting existing tests"
      - VALUE: "breaking-change"
        DESC: "🥹A breaking API change"
      - VALUE: "build"
        DESC: "🏗Changes that affect the build system or external dependencies"
      - VALUE: "ci"
        DESC: "💚Changes to our CI configuration files and scripts"
      - VALUE: "chore"
        DESC: "💊Other changes that don't modify src or test files"
      - VALUE: "revert"
        DESC: "🔙Reverts a previous commit"
  - KEY: "MODULE"
    LABEL: "Affected module"
  - KEY: "MESSAGE"
    INPUTS:
      - VALUE: "text"
        DESC: "Commit message"
      - VALUE: "comment"
        DESC: "Ask ChatGPT for suggestions of the comment [Coming soon]"
      - VALUE: "diff"
        DESC: "Ask ChatGPT for suggestions of code changes [Coming soon]"
COMMIT_TEMPLATE: "#{{PROJECT_NAME}}-{{REFERENCE}} {{CHANGE}}({{MODULE}}): {{MESSAGE}}"
BRANCH:
  - KEY: "REFERENCE"
    LABEL: "Task ID"
    PROJECT_NAME: "{{NAME}}"
  - KEY: "CATEGORY"
    LABEL: "Type of category"
    OPTIONS:
      - VALUE: "feature"
        DESC: "Used for new feature development"
      - VALUE: "refactor"
        DESC: "Used for refactoring existing code without adding new features"
      - VALUE: "bugfix"
        DESC: "Used for fixing bugs"
      - VALUE: "hotfix"
        DESC: "Used for fixing critical issues"
      - VALUE: "experimental"
        DESC: "Used for testing new features or ideas"
      - VALUE: "build"
        DESC: "Used for compiling and testing code in a dedicated environment"
      - VALUE: "release"
        DESC: "Used for preparing or stabilizing a release version"
      - VALUE: "merge"
        DESC: "Action to combine changes from one branch into another."
      - VALUE: "WIP"
        DESC: "Abbreviation for Work In Progress, indicating ongoing development"
      - VALUE: "maintenance"
        DESC: "Used for general maintenance tasks or non-functional changes"
  - KEY: "MESSAGE"
    LABEL: "Name of branch"
    SEPARATOR: "-"
    INPUTS:
      - VALUE: "text"
        DESC: "A branch name is that it should be short, precise and informative"
      - VALUE: "comment"
        DESC: "Ask ChatGPT for suggestions a branch name [Coming soon]"
BRANCH_TEMPLATE: "{{CATEGORY}}/{{PROJECT_NAME}}-{{REFERENCE}}_{{MESSAGE}}"